---
title: "COVID-19"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(tidyr)
library(dplyr)
library(leaflet)
library(plotly)
library(stringr)
library(RCurl)
library(tidyverse)
library(data.table)
library(maps)
library(geojson)
library(geojsonio)
library(geojsonlint)

#Import data:
world <- read.csv("COVID19_March_15_case_count.csv")

```
World Overview
=====================================  

Row
-----------------------------------------------
### Confirmed cases

```{r}

renderValueBox({
  confirmed_cases <- sum(world$Confirmed)
  valueBox(prettyNum(confirmed_cases, big.mark = ","),
           color = "maroon")
})
```

### Deaths 
```{r}
renderValueBox({
  deaths <- sum(world$Deaths)
  valueBox(prettyNum(deaths, big.mark = ","), 
           color = "black")
})
```

### Recovered 
```{r}
renderValueBox({
  recovered <- sum(world$Recovered)
  valueBox(prettyNum(recovered, big.mark = ","),
           color = "success")
})
```

Row {data-height=650}
--------------------------------------------
### Confirmed cases worldwide
    
```{r}

leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(world$Longitude, world$Latitude, 
                   radius = sqrt(world$Confirmed)/8,
                   fillColor = 'red',
                  color = "red",
                   weight = 3,
                   fill = T,
                   fillOpacity = 0.5,
                   opacity = 0.5,
                   popup = paste(world$Province.State, sep = " ", world$Country.Region, 
                                 world$Confirmed, "confirmed cases"))

```

Row {data-height = 50}
--------------------------------------------
### Search by country or region

```{r}

cases_df = world %>%
    select(Country.Region, Confirmed, Deaths, Recovered) 

cases_df1 = aggregate(x = cases_df[, 2:4], by = list(cases_df$Country.Region), FUN = sum)
colnames(cases_df1) = c("Country or Region", "Confirmed", "Deaths", "Recovered")
cases_df1 = cases_df1 %>% arrange(desc(Confirmed))
DT::renderDataTable({
DT::datatable(cases_df1,  rownames = TRUE, options = list(scrollY = '300px',pageLength = 5))
})
```

### Total number of cases worldwide over time
```{r}
time_series_confirmed = read.csv("time_series_19-covid-Confirmed.csv")
time_series_death = read.csv("time_series_19-covid-Deaths.csv")
time_series_recovered = read.csv("time_series_19-covid-Recovered.csv")

time_series_confirmed1 = aggregate(x = time_series_confirmed[, 5:58], by = list(time_series_confirmed$Country.Region), FUN = sum)
time_series_death1 = aggregate(x = time_series_death[, 5:58], by = list(time_series_death$Country.Region), FUN = sum)
time_series_recovered1 = aggregate(x = time_series_recovered[, 5:58], by = list(time_series_recovered$Country.Region), FUN = sum)

# calculate global trend on cases
dates = seq(as.Date("2020/1/22"), as.Date("2020/3/15"), "days")
confirmed_cases = colSums(time_series_confirmed1[,-1])
death = colSums((time_series_death1[,-1]))
recovered = colSums(time_series_recovered1[,-1])

global_trend = data.frame(Date = dates, confirmed_cases = confirmed_cases, death = death, recovered = recovered)
colnames(global_trend) = c("Date", "Confirmed cases", "Deaths", "Recovered")

p = ggplot() + 
  geom_line(data = global_trend, aes(x = Date, y = `Confirmed cases`), color = "blue", size = 1.5) +
  geom_line(data = global_trend, aes(x = Date, y = Deaths), color = "red", size = 1.5) +
  geom_line(data = global_trend, aes(x = Date, y = Recovered), color = "green", size = 1.5) +
  xlab('Date') +
  ylab('Number of cases') +
  theme_minimal() +
  scale_fill_discrete(name="Total cases over time",
                     labels=c("Confirmed cases", "Deaths", "Recovered"))

ggplotly(p)
```

Row
-----------------------------------------------
### **Note:** 
Created by **Vy Tran**. Case information was updated on **<u>March 15, 2020</u>**. <br />
Download codes and data on (Github) []


Vietnam Overview
===================================== 


Row
-----------------------------------------------
### Confirmed cases

```{r}
Vietnam = read.csv("Vietnam_cases_March_16.csv")
renderValueBox({
  confirmed_cases <- sum(Vietnam$Confirmed)
  valueBox(prettyNum(confirmed_cases, big.mark = ","),
           color = "maroon")
})
```

### Deaths 
```{r}
renderValueBox({
  deaths <- sum(Vietnam$Death)
  valueBox(prettyNum(deaths, big.mark = ","), 
           color = "black")
})
```

### Recovered 
```{r}
renderValueBox({
  recovered <- sum(Vietnam$Recovered)
  valueBox(prettyNum(recovered, big.mark = ","),
           color = "success")
})
```

Row {data-height=650}
-------------------------------------

### Distribution of cases in Vietnam
```{r}

# Create interactive labels for leaflet graph
labels <- sprintf(
  "<strong>%s</strong><br/>%s Confirmed <br/>%s Deaths<br/>%s Recovered",
  Vietnam$Province.City, Vietnam$Confirmed, Vietnam$Death, Vietnam$Recovered) %>% 
  lapply(htmltools::HTML)


# create a leaflet map on which we will build
leaflet() %>% 
  setView( lng = 106.7,
            lat = 15,
            zoom = 5.49) %>%
  addTiles() %>% 
  addCircleMarkers(Vietnam$lng, 
                   Vietnam$lat, 
                   radius = Vietnam$Confirmed,
                   fillColor = 'red',
                   color = 'red',
                   weight = 3,
                   fill = T,
                   fillOpacity = 0.6,
                   opacity = 0.6, label = labels)

```

Row
-----------------------------------------------
#### Cases in Vietnam by province

```{r}
Vietnam_cases = Vietnam %>%
    select(Province.City, Confirmed, Death, Recovered) 
colnames(Vietnam_cases) = c("Province or City", "Confirmed", "Death", "Recovered")
Vietnam_cases = Vietnam_cases%>% arrange(desc(Confirmed))
DT::renderDataTable({
DT::datatable(Vietnam_cases,  rownames = TRUE, options = list(scrollY = '300px',pageLength = 13))
})
```

Row
-----------------------------------------------
### **Note:** 
Case information was updated on **<u>March 15, 2020</u>**. 



